# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_url = "https://atlas.hashicorp.com/centos/boxes/7/versions/1611.01/providers/virtualbox.box"
  config.vm.network "forwarded_port", guest: 5006, host: 5006  # Bokeh server
  config.vm.provider :virtualbox do |vb|
    vb.name = "big-data-benchmarking"
    vb.memory = "1024"
  end
  config.vm.synced_folder "..", "/big-data-benchmarking"
  config.vm.provision :shell, :path => "scripts/provision.sh"
end
