# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_url = "https://atlas.hashicorp.com/centos/boxes/7/versions/1611.01/providers/virtualbox.box"
  config.vm.network :private_network, ip: "192.168.0.100"
  #config.vm.network "forwarded_port", guest: 8888, host: 8888
  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
  end
  config.vm.provision :shell, :path => "scripts/base.sh"
  config.vm.provision :shell, :path => "scripts/python3_install.sh"
  config.vm.synced_folder "..", "/big-data-benchmarking"
end
